name: CI/CD Backend

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: axelvergara/myapp-backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and test with Maven
        run: mvn clean verify

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image backend
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image backend
        run: docker push $IMAGE_NAME:$IMAGE_TAG
